using Code;

var input = """
...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
""".Trim().ReplaceLineEndings();


var inputFile = File.ReadAllText("./input.txt");
Console.WriteLine(Day11.Solve(inputFile, 2));